// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDR88ePTsqMnRhYCb-RezHEfVw27CY_Y8I',
    appId: '1:151848722794:android:f130dead6d2dbf02898513',
    messagingSenderId: '151848722794',
    projectId: 'flutter-realtime-chat-demo',
    storageBucket: 'flutter-realtime-chat-demo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFK59Kdk3_mUrvsZ5utItS3rk90Pmp7bc',
    appId: '1:151848722794:ios:e7deb04f7c23a51d898513',
    messagingSenderId: '151848722794',
    projectId: 'flutter-realtime-chat-demo',
    storageBucket: 'flutter-realtime-chat-demo.appspot.com',
    iosClientId: '151848722794-tse8fd57sbm6r3aoefcsvecl1i70hlg9.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterRealTimeChat',
  );
}
